package goog.ui.tree;
import js.Dom;
private typedef Object = Dynamic;
private typedef Node = Dom;
private typedef Element = HtmlDom;
private typedef HTMLIFrameElement = IFrame;
private typedef Selection = Dynamic;
private typedef Range = Dynamic;
private typedef HTMLElement = Element;
extern class BaseNode extends goog.ui.Component {
static function __init__(): Void {
        untyped __js__("goog.require('goog.ui.tree.BaseNode')");
      }
public function new( html:String,?opt_config:Dynamic,?opt_domHelper:Dynamic):Void;
 public function initAccessibility():Void;
 public function add( child:Dynamic,?opt_before:Dynamic):Dynamic;
 public function remove( child:Dynamic):Dynamic;
 public function getDepth():Float;
 public function computeDepth():Float;
 public function contains( node:Dynamic):Bool;
 public function getChildren():Dynamic;
 public function getFirstChild():Dynamic;
 public function getLastChild():Dynamic;
 public function getPreviousSibling():Dynamic;
 public function getNextSibling():Dynamic;
 public function isLastSibling():Bool;
 public function isSelected():Bool;
 public function select():Void;
 public function deselect():Void;
 public function getExpanded():Bool;
 public function setExpanded( b:Bool):Void;
 public function toggle():Void;
 public function expand():Void;
 public function collapse():Void;
 public function collapseChildren():Void;
 public function collapseAll():Void;
 public function expandChildren():Void;
 public function expandAll():Void;
 public function reveal():Void;
 public function setIsUserCollapsible( isCollapsible:Bool):Void;
 public function isUserCollapsible():Bool;
 public function toHtml( sb:Dynamic):Void;
 public function getRowHtml():String;
 public function getRowClassName():String;
 public function getLabelHtml():String;
 public function getAfterLabelHtml():String;
 public function setAfterLabelHtml( html:String):Void;
 public function getIconHtml():String;
 public function getExpandIconHtml():String;
 public function getExpandIconClass():String;
 public function getLineStyle():String;
 public function getLineStyle2():String;
 public function getRowElement():Dynamic;
 public function getExpandIconElement():Dynamic;
 public function getIconElement():Dynamic;
 public function getLabelElement():Dynamic;
 public function getAfterLabelElement():Dynamic;
 public function getChildrenElement():Dynamic;
 public function setIconClass( s:String):Void;
 public function getIconClass():String;
 public function setExpandedIconClass( s:String):Void;
 public function getExpandedIconClass():String;
 public function setText( s:String):Void;
 public function getText():String;
 public function setHtml( s:String):Void;
 public function getHtml():String;
 public function setToolTip( s:String):Void;
 public function getToolTip():String;
 public function update():Void;
 public function updateRow():Void;
 public function updateExpandIcon():Void;
 public function updateIcon():Void;
 public function onMouseDown( e:Dynamic):Void;
 public function getLastShownDescendant():Dynamic;
 public function getNextShownNode():Dynamic;
 public function getPreviousShownNode():Dynamic;
 public function getClientData():Dynamic;
 public function setClientData( data:Dynamic):Void;
 public function getConfig():Dynamic;
 public function onTreeAvailable():Void;
 public function setTreeInternal( tree:Dynamic):Void;
}
